import { App, Plugin, PluginSettingTab, Setting, WorkspaceLeaf, ItemView, Notice, TFile } from 'obsidian';
import { DRUG_DATA } from './src/data';

const VIEW_TYPE_OPIOID = "opioid-precision-tool-view";

class OpioidView extends ItemView {
    constructor(leaf: WorkspaceLeaf) {
        super(leaf);
    }

    getViewType() {
        return VIEW_TYPE_OPIOID;
    }

    getDisplayText() {
        return "Opioid Precision Tool";
    }

    async onOpen() {
        const container = this.contentEl;
        container.empty();
        container.addClass('opioid-tool-container');

        const iframe = container.createEl('iframe', {
            attr: {
                src: 'https://inpatient-opioid-tool.vercel.app',
                style: 'width: 100%; height: 100%; border: none;',
                sandbox: 'allow-scripts allow-forms allow-popups allow-same-origin'
            }
        });
    }

    async onClose() {
        // Nothing to unmount for iframe
    }
}

export default class OpioidPlugin extends Plugin {
    async onload() {
        this.registerView(
            VIEW_TYPE_OPIOID,
            (leaf) => new OpioidView(leaf)
        );

        this.addRibbonIcon('activity', 'Open Inpatient Opioid Tool', (evt: MouseEvent) => {
            this.activateView();
            this.trackPluginEvent('plugin_ribbon_open');
        });

        this.addCommand({
            id: 'open-opioid-tool-view',
            name: 'Open Opioid Precision Tool',
            callback: () => {
                this.activateView();
                this.trackPluginEvent('plugin_command_open');
            }
        });

        this.addCommand({
            id: 'sync-opioid-reference',
            name: 'Sync Medical Reference Notes',
            callback: async () => {
                await this.syncMedicalReference();
                this.trackPluginEvent('plugin_command_sync');
            }
        });
    }

    // Simple fire-and-forget tracking for the plugin side
    // We don't want to bundle the full PostHog node client here to keep it lightweight
    async trackPluginEvent(event: string) {
        // TODO: Replace with your actual Project API Key
        const POSTHOG_KEY = 'phc_INSERT_KEY_HERE';
        const POSTHOG_HOST = 'https://us.i.posthog.com';

        try {
            await fetch(`${POSTHOG_HOST}/capture/`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    api_key: POSTHOG_KEY,
                    event: event,
                    properties: {
                        distinct_id: 'plugin_user', // Anonymous user for plugin side
                        $lib: 'obsidian-plugin',
                        source: 'obsidian'
                    }
                })
            });
        } catch (e) {
            console.error("Failed to track plugin event", e);
        }
    }

    async syncMedicalReference() {
        const folderPath = 'Medical Reference/Opioid Tool';

        // Ensure folder exists
        let folder = this.app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
            await this.app.vault.createFolder(folderPath);
        }

        let createdCount = 0;

        for (const drug of DRUG_DATA) {
            const fileName = `${folderPath}/${drug.name}.md`;
            const content = `---
type: medication-reference
class: ${drug.type}
renal-safety: ${drug.renal_safety}
hepatic-safety: ${drug.hepatic_safety}
bioavailability: ${drug.bioavailability}%
tags: [${drug.tags.join(', ')}]
---
# ${drug.name}

## Clinical Nuances
${drug.clinical_nuance}

## Pharmacokinetics
${drug.pharmacokinetics}

---
*Generated by Inpatient Opioid Tool - ${new Date().toLocaleDateString()}*`;

            const existingFile = this.app.vault.getAbstractFileByPath(fileName);
            if (existingFile) {
                await this.app.vault.modify(existingFile as TFile, content);
            } else {
                await this.app.vault.create(fileName, content);
            }
            createdCount++;
        }

        new Notice(`Synced ${createdCount} clinical reference notes to ${folderPath}`);
    }

    onunload() { }

    async activateView() {
        const { workspace } = this.app;

        let leaf: WorkspaceLeaf;
        const leaves = workspace.getLeavesOfType(VIEW_TYPE_OPIOID);

        if (leaves.length > 0) {
            leaf = leaves[0];
        } else {
            leaf = workspace.getLeaf('tab');
            await leaf.setViewState({ type: VIEW_TYPE_OPIOID, active: true });
        }

        workspace.revealLeaf(leaf);
    }
}
