import { App, Plugin, PluginSettingTab, Setting, WorkspaceLeaf, ItemView, Notice, TFile } from 'obsidian';
import * as React from 'react';
import { createRoot, Root } from 'react-dom/client';
import OpioidPrecisionApp from './src/OpioidPrecisionApp';
import { DRUG_DATA, WARNING_DATA } from './src/data';

const VIEW_TYPE_OPIOID = "opioid-precision-tool-view";

class OpioidView extends ItemView {
    root: Root | null = null;

    constructor(leaf: WorkspaceLeaf) {
        super(leaf);
    }

    getViewType() {
        return VIEW_TYPE_OPIOID;
    }

    getDisplayText() {
        return "Opioid Precision Tool";
    }

    async onOpen() {
        const container = this.contentEl;
        container.addClass('opioid-tool-container');

        this.root = createRoot(container);
        this.root.render(
            React.createElement(React.StrictMode, null,
                React.createElement(OpioidPrecisionApp, null)
            )
        );
    }

    async onClose() {
        if (this.root) {
            this.root.unmount();
        }
    }
}

export default class OpioidPlugin extends Plugin {
    async onload() {
        this.registerView(
            VIEW_TYPE_OPIOID,
            (leaf) => new OpioidView(leaf)
        );

        this.addRibbonIcon('activity', 'Open Inpatient Opioid Tool', (evt: MouseEvent) => {
            this.activateView();
        });

        this.addCommand({
            id: 'open-opioid-tool-view',
            name: 'Open Opioid Precision Tool',
            callback: () => {
                this.activateView();
            }
        });

        this.addCommand({
            id: 'sync-opioid-reference',
            name: 'Sync Medical Reference Notes',
            callback: async () => {
                await this.syncMedicalReference();
            }
        });
    }

    async syncMedicalReference() {
        const folderPath = 'Medical Reference/Opioid Tool';

        // Ensure folder exists
        let folder = this.app.vault.getAbstractFileByPath(folderPath);
        if (!folder) {
            await this.app.vault.createFolder(folderPath);
        }

        let createdCount = 0;

        for (const drug of DRUG_DATA) {
            const fileName = `${folderPath}/${drug.name}.md`;
            const content = `---
type: medication-reference
class: ${drug.type}
renal-safety: ${drug.renal_safety}
hepatic-safety: ${drug.hepatic_safety}
bioavailability: ${drug.bioavailability}%
tags: [${drug.tags.join(', ')}]
---
# ${drug.name}

## Clinical Nuances
${drug.clinical_nuance}

## Pharmacokinetics
${drug.pharmacokinetics}

---
*Generated by Inpatient Opioid Tool - ${new Date().toLocaleDateString()}*`;

            const existingFile = this.app.vault.getAbstractFileByPath(fileName);
            if (existingFile) {
                await this.app.vault.modify(existingFile as TFile, content);
            } else {
                await this.app.vault.create(fileName, content);
            }
            createdCount++;
        }

        new Notice(`Synced ${createdCount} clinical reference notes to ${folderPath}`);
    }

    onunload() { }

    async activateView() {
        const { workspace } = this.app;

        let leaf: WorkspaceLeaf;
        const leaves = workspace.getLeavesOfType(VIEW_TYPE_OPIOID);

        if (leaves.length > 0) {
            leaf = leaves[0];
        } else {
            leaf = workspace.getLeaf('tab');
            await leaf.setViewState({ type: VIEW_TYPE_OPIOID, active: true });
        }

        workspace.revealLeaf(leaf);
    }
}
