#if canImport(UIKit)
import UIKit
#endif
import Foundation

class NoteGenerator {
    static func generateSOAP(store: AssessmentStore) -> String {
        var note = ""
        let date = Date().formatted(date: .abbreviated, time: .shortened)
        
        // --- HEADER ---
        note += "PAIN MANAGEMENT CONSULT NOTE\n"
        note += "Generated: \(date)\n\n"
        
        // --- SUBJECTIVE / CONTEXT ---
        note += "**SUBJECTIVE / CONTEXT**\n"
        // 1. Create the Age String (Logic Fix)
        // If age exists -> "45yo". If nil -> "Adult"
        let ageDescription: String = {
            if !store.age.isEmpty {
                return "\(store.age)yo"
            } else {
                return "Adult"
            }
        }()
        
        note += "Patient: \(ageDescription) \(store.sex.rawValue)\n"
        note += "Indication: \(store.indication.rawValue)\n"
        note += "Baseline Profile: \(store.analgesicProfile.rawValue)"
        if !store.currentMME.isEmpty { note += " (~ \(store.currentMME) MME)" }
        note += "\n"
        
        // Comorbidities (Positive findings only)
        var history: [String] = []
        if store.renalFunction.isImpaired { history.append("Renal Impairment (\(store.renalFunction.rawValue))") }
        if store.hepaticFunction != .normal { history.append("Hepatic Impairment (\(store.hepaticFunction.rawValue))") }
        if store.sleepApnea { history.append("OSA") }
        if store.benzos { history.append("Concurrent Benzodiazepines") }
        if store.qtcProlonged { history.append("Prolonged QTc") }
        if store.historyOverdose { history.append("Hx Overdose") }
        
        if !history.isEmpty {
            note += "Relevant PMH: " + history.joined(separator: ", ") + "\n"
        }
        note += "\n"
        
        // --- ASSESSMENT (The "Why") ---
        note += "**ASSESSMENT**\n"
        note += "1. \(store.painType.rawValue) Pain"
        if store.inflammatorySubtype != .none { note += " (\(store.inflammatorySubtype.rawValue))" }
        note += "\n"
        
        note += "2. OIRD Risk Stratification: \(store.prodigyRisk.uppercased())\n"
        note += "   - Risk Score: \(store.compositeOIRDScore)\n"
        
        // --- PLAN (The "What") ---
        note += "\n**PLAN**\n"
        
        // 1. Primary Analgesia
        if !store.recommendations.isEmpty {
            note += "1. Pharmacologic Analgesia:\n"
            for rec in store.recommendations {
                let prefix = rec.type == .safe ? "[Preferred]" : "[Caution]"
                note += "   - \(prefix) \(rec.name): \(rec.detail)\n"
            }
        }
        
        // 2. Adjuvants (Multimodal)
        if !store.adjuvants.isEmpty {
            note += "2. Multimodal / Adjuvants:\n"
            for adj in store.adjuvants {
                note += "   - \(adj.drug): \(adj.dose) (\(adj.rationale))\n"
            }
        }
        
        // 3. Monitoring / Stewardship
        if !store.monitoringPlan.isEmpty {
            note += "3. Safety & Monitoring:\n"
            for monitor in store.monitoringPlan {
                note += "   - \(monitor)\n"
            }
        }
        
        // 4. Exclusions (Defensive Medicine)
        // This is HUGE for interns justifying decisions to attendings
        if !store.warnings.isEmpty {
            note += "4. Clinical Alerts & Exclusions:\n"
            for warn in store.warnings {
                note += "   - \(warn)\n"
            }
        }
        
        note += "\n---\n"
        note += "Generated by Opioid Precision. Clinical judgment required."
        
        return note
    }
}
